# Generated by Django 5.2.14 on 2026-07-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sboms", "0064_alter_component_is_global"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sbom",
            name="sboms_sbom_unique_component_version_format_qualifiers_bom_type",
        ),
        migrations.AddConstraint(
            model_name="sbom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("bom_type", "vex"), _negated=True),
                fields=("component", "version", "format", "qualifiers", "bom_type"),
                name="sboms_sbom_unique_component_version_format_qualifiers_bom_type",
            ),
        ),
    ]
