# Generated by Django 5.2.14 on 2026-07-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_delete_productproject_delete_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="releaseartifact",
            name="auto_pinned",
            field=models.BooleanField(
                default=False,
                help_text="Pinned by sbomify to track the component's newest VEX. Auto pins are re-pointed when a newer VEX appears; a manually pinned VEX is an authoritative snapshot and is never replaced automatically.",
            ),
        ),
    ]
