# Generated by Django 5.2.12 on 2026-04-22 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0005_add_bsi_waivers"),
        ("teams", "0034_alter_team_security_txt_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamComplianceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signing_enabled", models.BooleanField(default=False)),
                (
                    "signing_provider",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("sigstore_keyless", "Sigstore (keyless, Fulcio)"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                (
                    "signing_identity",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_settings",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_team_settings",
            },
        ),
    ]
