# Generated by Django 5.2.12 on 2026-04-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0006_add_team_compliance_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="craexportpackage",
            name="signature_provider",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="craexportpackage",
            name="signature_storage_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
