# Generated by Django 5.2.12 on 2026-04-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0007_add_signature_fields_to_export_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="craexportpackage",
            name="rekor_log_index",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="craexportpackage",
            name="signed_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="craexportpackage",
            name="signed_issuer",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="teamcompliancesettings",
            name="signing_issuer",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
