# Generated by Django 5.2.12 on 2026-04-24 12:10

import django.db.models.deletion
import sbomify.apps.core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0012_tighten_annex_part_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="craassessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_progress", "In Progress"),
                    ("complete", "Complete"),
                    ("stale", "Stale (scope changed)"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CRAReportSubmission",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=sbomify.apps.core.utils.generate_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("early_warning", "Early Warning (24h)"),
                            (
                                "vulnerability_notification",
                                "Vulnerability Notification (72h)",
                            ),
                            ("final_report", "Final Report (14d)"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("failed", "Failed"),
                            ("adapter_not_configured", "Adapter not configured"),
                        ],
                        default="pending",
                        max_length=40,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                (
                    "payload",
                    models.JSONField(
                        help_text="The report body the service attempted to submit"
                    ),
                ),
                (
                    "acknowledgement",
                    models.JSONField(
                        blank=True,
                        help_text="Opaque SRP response envelope returned on successful submit",
                        null=True,
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Transport/adapter error captured on FAILED or ADAPTER_NOT_CONFIGURED submissions",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the SRP acknowledged the submission",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_submissions",
                        to="compliance.craassessment",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        help_text="Operator who triggered the submission",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cra_report_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compliance_cra_report_submissions",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("idempotency_key",),
                        name="cra_report_submission_idem_key_unique",
                    )
                ],
            },
        ),
    ]
